services:
  file-storage-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL="mysql://root:password@file-db/file-db"
      - RABBIT_ADDRESS="amqp://guest:guest@rabbit-mq:5672"
    depends_on:
      file-db:
        condition: service_healthy

  file-db:
    image: mysql:9.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: file-db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit-mq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  db_data:
